### ISSUE TITLE
Module not found 

### ISSUE THREAD

**Issue by alikahwaji** [fegyi001/mangol#25]
After running the example in angular 6, I get this error:

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'mangol' in '/Users/{{userName}}/workspace/mangol/example_project/src/app' 

any ideas how to solve this ?

**Comment by Richard-Rumpel** [comment]
Same problem here. did you find a solution ?

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'mangol' in '/[name removed]/src/app'

webpack: Failed to compile.
ERROR in src/app/app.module.ts(55,30): error TS2307: Cannot find module 'mangol'.

**Comment by fegyi001** [comment]
@alikahwaji , @Richard-Rumpel I just published a fresh version of Mangol which is completely rewritten for Angular6+. Please check whether it solves your problem. 
But the API has changed a bit, please visit the github main Readme to see how MangolConfig should be configured from now on.

**Comment by alikahwaji** [comment]
@fegyi001 thanks for the new version really appreciate it. 
@Richard-Rumpel , until seeing the new version today, no I didn't find an solution.

**Comment by Richard-Rumpel** [comment]
@alikahwaji did it work ?! i have updated to the last version of mangol - it's still not working.
